version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:9000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
      MYSQLDB_USER: root
      MYSQLDB_ROOT_PASSWORD: mysql_password
      MYSQLDB_DATABASE: vacation
      MYSQLDB_HOST: mysql
      MYSQLDB_LOCAL_PORT: 3306
      MYSQLDB_DOCKER_PORT: 3306
      JWT_ACCESS_SECRET: secret
      JWT_REFRESH_TOKEN: secret12
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: vacation
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

